[package]
name = "builder"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
regex = { version = "1.8.1", default-features = false, features = ["std", "unicode-perl"] }
zip = "0.6.5"
flate2 = { version = "1.0.26", features = ["zlib"], default-features = false }
