[package]
name = "builder"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[dependencies]
anyhow = "1.0.9"
regex = { version = "1.3.1", default-features = false, features = ["std", "unicode-perl"] }
zip = "0.5.3"
flate2 = { version = "1.0.17", features = ["zlib"], default-features = false }