[package]
name = "no-std-examples"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
publish = false

[features]
std = ["rune/std"]

[dependencies]
rune = { path = "../crates/rune", default-features = false, features = ["alloc"] }
wee_alloc = "0.4.5"
