name: Nightly Build

on:
  schedule:
    - cron:  '* 1 * * *'
  push:
    branches:
      - nightly

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --all
    - run: cargo run --release --bin rune -- check --recursive --experimental scripts
    - run: cargo run --manifest-path tools/builder/Cargo.toml -- --channel nightly
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: nightly
        files: target/upload/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
